### ISSUE TITLE
Urgent Help - Failed resolution of FirebaseStorgae.getInstance Unknown

### ISSUE THREAD

**Issue by aliexalter** [scottrules44/firebaseStorage-demo#1]
Hi,
I cannot initialize firebaseStorage correctly. I am getting following error.
<img width="1310" alt="screenshot 2019-01-17 at 22 53 18" src="https://user-images.githubusercontent.com/2280503/51338076-b41be400-1aaa-11e9-80c8-203d5092b12e.png">

Here is my code
`
```
local firebaseDatabase = require "plugin.firebaseDatabase"
local firebaseStorage = require "plugin.firebaseStorage"

-- include Corona's "widget" library
local widget = require "widget"
firebaseDatabase.init()
timer.performWithDelay( 100, function()
    	firebaseStorage.init("gs://api-project-1230000000.appspot.com/")
    end)
```
`

**Comment by scottrules44** [comment]
This should be patched

**Comment by scottrules44** [comment]
Have not heard back, but this should have been patched
