### ISSUE TITLE
The default Firebase app has not yet been configured. 

### ISSUE THREAD

**Issue by dinkuraja** [scottrules44/firebaseStorage-demo#2]
I am getting this error while using the demo code as well as my own code...

Error:

5.20.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.

**Comment by scottrules44** [comment]
please file a bug report here
https://docs.google.com/forms/d/e/1FAIpQLSf-V3z-V3FZ5y9Sb19cxVfjx7fSRV9HIbpAGptN7DaY3Ki_DA/viewform
